services:
  my-service:
    image: labeltool.heinrichstefan.eu/deploy:latest
    container_name: Ph-deploy
    volumes:
      - ${HOME}/Documents/:/root/Documents/
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/dbus:/var/run/dbus:rw
      - /run/NetworkManager:/run/NetworkManager:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    privileged: true
    devices:
      - "/dev/bus:/dev/bus"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia # Ensure NVIDIA runtime is used
    network_mode: "host" # Use host network mode
